export const header: string
export const linkContainer: string
export const linkContainer_menu: string
export const linkContainer_menu_open: string
export const linkWrapper: string
export const menuBtn: string
export const menuBtn_burger: string
export const open: string
export const btnVisible: string
